<?php

/**
 * @Author: Akhil Anand
 * @Date:   2017-10-29 21:58:28
 * @Last Modified by:   Akhil Anand
 */

namespace AK\StoreSelector\Block;

use Magento\Framework\App\Request\Http;
use Magento\Framework\View\Element\Template\Context;
use Magento\Store\Api\StoreRepositoryInterface;

class StoreSelector extends \Magento\Framework\View\Element\Template
{
    /*
     * Magento\Store\Api\StoreRepositoryInterface
     */
    private $stores;

    /**
     * @var Http
     */
    private $request;

    /**
     * Retrieve form action url and set "secure" param to avoid confirm
     * message when we submit form from secure page to unsecure
     *
     * @param Context $context
     * @param StoreRepositoryInterface $stores
     * @param Http $request
     * @param array $data
     */
    public function __construct(
        Context $context,
        StoreRepositoryInterface $stores,
        Http $request,
        array $data = []
    ) {
        $this->stores = $stores;
        $this->request = $request;
        parent::__construct($context, $data);
    }

    /**
     * @return \Magento\Store\Api\Data\StoreInterface[]
     */
    public function getStores()
    {
        return $stores = $this->stores->getList();
    }

    /**
     * @return bool
     */
    public function isHomePage()
    {
        if ($this->_request->getFullActionName() == 'cms_index_index') {
            return true;
        }

        return false;
    }

    public function getAjaxUrl()
    {
        return parent::getBaseUrl().'visitors/index/index'; // TODO: Change the autogenerated stub
    }
}
